name: fw_app_workspace
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  dart_mappable: ^4.0.1
  build_runner: ^2.4.7
  dart_mappable_builder: ^4.2.0
  melos: ^3.1.0
dependencies:
  dart_mappable: ^4.2.0
