builders:
  dart_mappable_builder:
    import: "package:dart_mappable_builder/dart_mappable_builder.dart"
    builder_factories: [ "buildMappable" ]
    build_extensions: { ".dart": [ ".mapper.dart", ".init.dart" ] }
    required_inputs: [".freezed.dart"]
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - test/integration/**/*_test.dart
